### ISSUE TITLE
Uneinheitliche Namen!

### ISSUE THREAD

**Issue by AresCrew** [AnonymOnline/btw17#100]
Warum heißen die Tabellen 1stimme und 2stimme mit kleinem S aber die spalten 1Anzahl und 2Anzahl mit großem A?

**Comment by AresCrew** [comment]
Dazu kommt:
Warum heißt die Tabelle für die Direktkandidaten "Direktkandidaten" (Mehrzahl), aber die Tabelle für die Parteien heißt "Partei" (Einzahl).

**Comment by cybertschunk** [comment]
Das ist nunmehr halt so. Wir werden jetzt nicht anfangen die Tabellen umzubenennen.
