### ISSUE TITLE
Wo ist David?

### ISSUE THREAD

**Issue by Henningen22** [AnonymOnline/btw17#104]
Frau Friedemann erbittet vorherige Mitteilungen, bei arbeiten Zuhause.

**Comment by cybertschunk** [comment]
Das tut mir sehr leid. Das habe ich dann falsch verstanden. Soll ich jetzt noch kommen?

**Comment by Henningen22** [comment]
Alles gut, du sollst nur mitteilen, dass du am Projekt arbeitest. ;)
