### ISSUE TITLE
missing << "\n" in database.cpp and databasedialog.cpp

### ISSUE THREAD

**Issue by kilian-krause** [AnonymOnline/btw17#111]
bitte darauf achten das am ende der Anweißung immer << "\n" steht (selber lössen oder meine geänderte Datei nehmen)

**Comment by cybertschunk** [comment]
Viele fehlende Zeilenumbrüche sind in der aktuellen Version in master bereits vorhanden. Die Übrigen habe ich eigentlich alle in meinem aktuellen Entwicklungs-Branch (write-renderengine) ergänzt.

**Comment by kilian-krause** [comment]
sehr gut hatte nur zu ein paar fehlern mit dem Logger geführt
