### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#12]
Wir brauchen einen Server für die Entwicklung.
Ich würde diesen hier vorschlagen: https://www.hetzner.de/hosting/produkte_vserver/cx10

**Comment by cybertschunk** [comment]
@Henningen22 Haben wir jetzt einen Server?

**Comment by Henningen22** [comment]
@AnonymOnline Mein treffen mit Frau Bachmann ist am 23.05 sie hat einen vollen Kalender. Ich werde ihr dann den Brief vorlegen und bin zuversichtlich, dass der server zum 1.6 da ist

**Comment by cybertschunk** [comment]
Der Server steht und ist weitestgehend eingerichtet.
