### ISSUE TITLE
Begrenzung der int Tabellen

### ISSUE THREAD

**Issue by Henningen22** [AnonymOnline/btw17#121]
Die verschiedenen Relationen werden mit int (4) oder 1Anzahl sogar mit int(2) begrenzt. Die Website trägt dies trotzdem in die Datenbank ein, auch wenn es über die Begrenzung geht. Kann ich diesen Fehler beheben ohne etwas durcheinander zu bringen, was mit der Visualisierung oder den Abfragen zu tun hat? Wenn nicht würde ich es so lassen.

**Comment by HasseDosch** [comment]
int(4) bedeutet nicht, dass nur 4 stellige Zahlen eingegeben werden können
siehe [mysql-documentation](https://dev.mysql.com/doc/refman/5.5/en/numeric-type-attributes.html)
