### ISSUE TITLE
was ist "richtig" und was "falsch"

### ISSUE THREAD

**Issue by HasseDosch** [AnonymOnline/btw17#122]
Im wiki steht, dass die Datenbank für dieses Jahr `_wp_BTW_DE_17` heißt, im config file allerdings `_wp_BTW_DE_2017`.
Fakt ist, dass wir uns auf ein Schema einigen müssen, da wirklich keiner ständig irgendwelche config files oder gar gleich Datenbanken ändern will!

**Comment by HasseDosch** [comment]
ich werde jetzt alles in `_wp_BTW_DE_2017` ändern ...

**Comment by cybertschunk** [comment]
%JAHR% = Das Jahr, in dem die Wahl stattfindet - vollständig ausgeschrieben. Was im Wiki steht gilt.

**Comment by HasseDosch** [comment]
genau und das was im wiki steht widerspricht sich nunmal selbst, vollständig ausgeschrieben ist im wiki Beispiel `_wp_BTW_DE_17`

**Comment by HasseDosch** [comment]
ich habe jetzt soweit alles angepasst
