### ISSUE TITLE
Hat jemand die Bspdatensätze importiert?

### ISSUE THREAD

**Issue by HasseDosch** [AnonymOnline/btw17#129]
Ich bin grade auf dem Server und sehe etwas was uns morgen hätte den Tag versauen können. Anscheinend hat jemand die vorherigen Kandidaten und Parteien überschrieben, wer? Hat derjenige noch die import-zeilen für die richtigen dieses Jahr? Derjenige hat haue verdient! Wäre morgen doof mit den Falschen Kandidaten...

**Comment by Henningen22** [comment]
Ui, warst wohl noch eingeloggt. Nicht gemerkt. @HasseDosch

**Comment by cybertschunk** [comment]
@Henningen22 ist das geklärt?
