### ISSUE TITLE
Design for Settingswindow

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#13]
@infolk11/vwahl  We need to create a design for the Settingswindow.

**Comment by cybertschunk** [comment]
@HasseDosch  @Steve-F333 I'll take care of this problem. I've already created a basic plan for the design.
![settingswindow design](https://cloud.githubusercontent.com/assets/21140322/26283560/6fe008aa-3e2b-11e7-944e-0874a61e9e91.jpg)
I've also started to implement it. See commit [3fd68278f184d34d14b13e1ced09e98df5d86d0e](https://github.com/infolk11/btw17/commit/3fd68278f184d34d14b13e1ced09e98df5d86d0e) for more details. If you have any ideas how to improve my plan just tell me. I'll keep this issue open.

**Comment by Anonym0nline** [comment]
sorry for the late response, i like the design and the possibilities for a good presentative overview, given through it. i would recommend a submit button, to change the settings without changes in the main window and push them all-in-one to the main window.

**Comment by cybertschunk** [comment]
@Anonym0nline there is already a submit-button called 'anzeigen'
