### ISSUE TITLE
Verbindung Direktkandidat-Partei

### ISSUE THREAD

**Issue by ghost** [AnonymOnline/btw17#14]
Es fehlt eine Möglichkeit einzusehen, welcher Partei ein Direktkandidat angehört oder ob er evnt. parteilos ist.

**Comment by cybertschunk** [comment]
@Grasotus bitte bei einem Issue immer die Leute "Assigneen", die sich darum kümmern sollen. Im Idealfall nennst du sie außerdem im Kommentar @Henningen22 @Karl168 . Es guckt schließlich nicht jeder von uns jeden Tag inst GitHub-Repo. :-)

**Comment by ghost** [comment]
Oh vielen lieben Dank für den Hinweis, das war mir neu ^^

**Comment by HasseDosch** [comment]
Ich weiß aktuell nicht wie das Modell der Datenbank in SQL umgesetzt ist. Allerdings gibt es im Modell die "stellt" Beziehung die einen Kandidaten mit einer Partei verbindet. Meines Erachtens kann das Problem gelöst werden indem es einen Eintrag in der Partei Tabelle mit der Bezeichnung "parteilos" gibt. Allerdings muss dann die Kardinalität von 1:1 in 1:n geändert werden, da natürlich mehrere Kandidaten parteilos sein können.
Einen NULL wert für parteilose Kandidaten in der "stellt" Relation halte ich persönlich für nicht empfehlenswert da dies an dieser Stelle schnell zu Problemen mit den Primär -bzw. Fremdschlüsseln führen kann.

**Comment by cybertschunk** [comment]
@HasseDosch schließe mich dir an ;-)

**Comment by Henningen22** [comment]
@infolk11/infolk Hey Leute ich möchte nochmal kurz zu den Bugs oben was loswerden, ich bin kein Profi in phpmyadmin und ich verstehe teilweise nichtmal die Probleme oben. Das Ding ist, dass wir es alle schleifen lassen haben und jetzt wird es eng. Ihr seht überall im Thema voll durch, ihr könntet sowas schnell beheben. Aber wir können das halt nicht so gut und müssen erstmal googlen und kleistern dann etwas zusammen wobei wir nichtmal wissen ob der Fehler damit behoben ist. Ich bitte euch am Dienstag nicht das schleppende Vorankommen auf uns zu schieben, wir können es halt nicht so gut. Wir tuen was unsere Zeit zulässt und unser Kopf, aber mehr geht irgendwie nicht. Durchlesen, ernst nehmen. Danke

**Comment by cybertschunk** [comment]
Dieser Issue wurde in #34 aufgenommen.
