### ISSUE TITLE
So many branches

### ISSUE THREAD

**Issue by HasseDosch** [AnonymOnline/btw17#20]
From time to time we should merge our different branches. Otherwise we will force problems, today I could not compile our code because I had an error in one of our xml files. And I have no idea where this did come from. Currently we have development, plotting and graphics for almost the same work to do. This is will end up in chaos, if we do not fix it yet.
@AnonymOnline @Steve-F333 @Anonym0nline

**Comment by ghost** [comment]
Sorry if I'm screwing things up, but I'm not quite sure how to operate on this website ^^' It would be nice if you could help me out with organising my files

**Comment by cybertschunk** [comment]
@Grasotus I guess you aren't ment with this issue? :)

**Comment by cybertschunk** [comment]
@HasseDosch I've now radicaly reduced the active  branches. The code should be compileable now.
