### ISSUE TITLE
Using sql variables in Qt

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#33]
Using sql variables in qt should be quite simple. https://doc.qt.io/qt-5/qsqlquery.html#bindValue

**Comment by HasseDosch** [comment]
We should also take a look at [preparing](https://doc.qt.io/qt-5/qsqlquery.html#prepare) sql-querys in order to use binding values.

**Comment by Anonym0nline** [comment]
why is this an issue?

**Comment by cybertschunk** [comment]
works perfectly
