### ISSUE TITLE
bestimmte Abfragen nicht möglich, da Datenbankstruktur unvollständig

### ISSUE THREAD

**Issue by HasseDosch** [AnonymOnline/btw17#34]
Bspw. sind diese Art von Abfragen nicht möglich
```sql
-- alle Kandidaten mit zugehöriger Partei (wenn vorhanden), geordnet nach Nachname (A-Z)  
SELECT Vorname, Name, P_Bezeichnung
FROM direktkandidaten d, partei p
WHERE d.p_id = p.p_id ORDER BY Nachname;
```
, weil offenbar ein Attribut (P_ID[als Fremdschlüssel]) für Direktkandidaten fehlt ...

MariaDB [wahl17]> select * from direktkandidaten;
+------+---------+------------+
| D_ID | Vorname | Name       |
+------+---------+------------+
|    1 | Jack    | Daniels    |
|    2 | Michael | Myers      |
|    3 | Testi   | McTestface |
|    4 | Walter  | Meier      |
|    5 | Gary    | Eich       |
+------+---------+------------+

MariaDB [wahl17]> select Vorname, Name, P_Bezeichnung from direktkandidaten d, partei p
    -> where d.p_id = p.p_id order by Nachname;
ERROR 1054 (42S22): Unknown column 'd.p_id' in 'where clause'

Ich schlage folgende Vorgehensweise vor:

- [x]  Anpassen der Datenbank
- [ ]  Überarbeiten der Abfragen

Gerade bei Abfragen und Struktur sollten wir sehr "pingelig" sein (p_id statt P_ID, Nachname statt Name), andernfalls bekommen wir es später "doppelt und dreifach" zurück wenn Abfragen und Struktur auf Server, Website und  Visualisierungs-Anwendung geändert werden müssen.

**Comment by HasseDosch** [comment]
Ursprünglich sollte es sogar eine Relation "stellt" zwischen Partei und Direktkandidat geben, die gibt es bislang auch nicht.

**Comment by Henningen22** [comment]
Ja, ich habe auch noch eine ausstehende Aufgabe zur einfügung einer Relation bekommen. Ich hab das Gefühl das schleift wieder wegen uns. Ich mach mich morgen mal dran wenn ich eine aktuelle Version der Datenbank finde.

**Comment by KimPP** [comment]
Das wäre super! @Henningen22 Weil wir das auch brauchen um weiter zu arbeiten. @HasseDosch Wir hatten auf eine Änderung in der Datenbank gehofft und gewartet, sollte die Änderung dann so ausfallen, dass unsere Abfragen trotzdem nicht funktionieren ändern wir sie natürlich nochmal um! Vielen Dank trotzdem nochmal für den Hinweis

**Comment by cybertschunk** [comment]
@Henningen22 wie ist der Stand? Braucht ihr Hilfe?

**Comment by cybertschunk** [comment]
@Henningen22 @HasseDosch  wie ist der Stand?

**Comment by Henningen22** [comment]
Müsste jetzt funktionieren denk ich?

**Comment by cybertschunk** [comment]
okay, dann schließe ich den issue jetzt.

**Comment by Henningen22** [comment]
Ich müsste es nochmal probieren aber das geht grade nicht
