### ISSUE TITLE
Do we need that much classes?

### ISSUE THREAD

**Issue by Anonym0nline** [AnonymOnline/btw17#4]
Is is necessary to create 2 files per databasetable (header and source file)? If we need to create an object  (weather struct or class), we could define them inline. 

I would prefer to call a lambda or another funtcion to process the query. I don't think that we need the SQL results for more than one use, since we ask the database for specific data to change our visualization.

**Comment by cybertschunk** [comment]
You are right,
but I guess we will fix that laterwards, when everything else works fine.
