### ISSUE TITLE
Datenbankfehler P_ID in direktkandidaten

### ISSUE THREAD

**Issue by ghost** [AnonymOnline/btw17#45]
Die Partei eines Direktkandidaten wird über die Relation "stellt" ausgegeben. Dementsprechend dürfte die P_ID beim direktkandidaten unnötig sein.

**Comment by ghost** [comment]
Anders herum wäre es wahrscheinlich noch besser, wenn man die Relation "stellt" entfernt und die P_ID bei den direktkandidaten in die Beispieldatensätze aufnimmt.

**Comment by KimPP** [comment]
Uns fehlt auch noch immer die Extra Tabelle für die Stimmenanzahl pro Partei in Prozent, damit wir die Auswertung für Neuruppin als Bundestag angehen können, oder habe ich die übersehen? @Henningen22 @Karl168

**Comment by Henningen22** [comment]
Hast du nicht, hab ich noch nicht hoch geladen^^ @KimPP

**Comment by Henningen22** [comment]
Die Relation "stellt" zu löschen steht zwar zur wahl aber wäre dumm, weil wir die nur auf Wunsch eingefügt haben.

**Comment by HasseDosch** [comment]
#49
