### ISSUE TITLE
Bitte ALLLE Anfragen der Datenbankstruktur anpassen

### ISSUE THREAD

**Issue by HasseDosch** [AnonymOnline/btw17#58]
Beispielsweise funktionieren folgende Abfragen nicht ( aus dem .conf file)

MariaDB [wahl17]> SELECT ID, Vorname, Name FROM Direktkandidaten;
ERROR 1054 (42S22): Unknown column 'ID' in 'field list'
MariaDB [wahl17]> SELECT Vorname, Name, P_Bezeichnung FROM Direktkandidaten D, Partei P WHERE D.P_ID = P.P_ID ORDER BY Name;
ERROR 1054 (42S22): Unknown column 'D.P_ID' in 'where clause'

Ich weiß, dass dies eine mühselige Arbeit ist, allerdings muss die Abfragen-Gruppe auf jede Änderung in der Datenbankstruktur reagieren. Es ist auch nicht das erste mal, dass irgendetwas mit der Groß- und Kleinschreibung nicht funktioniert. Für die Arbeit der Visualisierungs-Gruppe sind diese nunmal elementar und daher ist deren Funktionstüchtigkeit überaus wichtig.

Aus meiner Sicht ist es sinnvoll jedesmal wenn es eine "neue" Datenbankstruktur gibt, diese zu übernehmen und die Testdaten einzufügen, um anschließend jede einzelne Abfrage zu testen. Falls die Testdaten gar nicht erst eingefügt werden können ist sollte dies umgehend der Datenbankgruppe mitgeteilt werden, damit die Fehler behoben werden können.
Es ist nicht schlimm falls einzelne Dinge nicht so funktionieren, wie sie sollten. Allerdings sollten alle Sachen die im master branch sind tip top funktionieren, damit mit diesen bereits gearbeitet werden kann.

**Comment by ghost** [comment]
Die Fehler wurden bereits im 12blank-patch-1 behoben, wenn ich das richtig sehe. Wurde der Branch bereits mit master gemerged?

**Comment by HasseDosch** [comment]
Naja dann ist doch alles gut, dann können Pull requests "requested" werden
