### ISSUE TITLE
Diagrammdesign

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#60]
@Steve-F333 kannst du bis Mitte Juli die verschiedenen Diagrammdesigns fertigstellen?

**Comment by HasseDosch** [comment]
@Steve-F333 kümmert du dich darum noch oder ist das schon erledigt?

**Comment by kilian-krause** [comment]
sind unter btw17/visualisierung/img/ und die letzte Datei habe ich gerade hochgeladen (war vorher eine .pdn und keine .png)

**Comment by cybertschunk** [comment]
okay
