### ISSUE TITLE
Datenbank mit Realdaten anreichern

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#62]
Bitte die Realdaten zum Testen einfügen.

**Comment by Henningen22** [comment]
@sidneygorgasfilmmaking  magst du das machen, wenn du grade zeit hast? wenn nicht kann ich mich dran setzen

**Comment by sidde-jpg** [comment]
Ja was denn? Also was soll ich machen? Die Kartoffelbilder suchen? xD

**Comment by Henningen22** [comment]
Nein, daten aus der letzten btw in die normale datenbank einfügen

**Comment by sidde-jpg** [comment]
Ich hätte genau jetzt Zeit xD

**Comment by Henningen22** [comment]
Na super

**Comment by sidde-jpg** [comment]
Ja Süßi, das tut mir leid, aber ich habe viel zu viel Zeit, ich mach das für dich.

**Comment by Henningen22** [comment]
Da oben steht, dass du jetzt Zeit hast, also mach das 🗡

**Comment by sidde-jpg** [comment]
Ich brenne deine Hütte ab! Danach schenke ich dir 1Millionen Euro und kauf dir ein neues Haus.

**Comment by Henningen22** [comment]
Danke @sidneygorgasfilmmaking ❤️

**Comment by sidde-jpg** [comment]
Halt die Fresse, ich hab keine Zeit jetzt du Sack. Du musst bestimmt nur Battlefield zocken oder ins Tasca. Is das jetzt so wichtig? Ich kann echt nich.

**Comment by Henningen22** [comment]
Ich mache grade Geschichte Hase. Ich suche nachher mal Daten Raus.

**Comment by sidde-jpg** [comment]
Muss das jetzt noch jemand machen? Dann würde ich das machen.

**Comment by Henningen22** [comment]
Ich habe grade angefangen mit Daten aus 2013. Lade die heute Nachmittag hoch, dann kannst du weiter machen.

**Comment by sidde-jpg** [comment]
Zum Sack, mir fällt grad erst auf dass du die Comments bearbeitet hast du Penner. Als Entschuldigung musst du mir nen Eis kaufen! Dummer Penner 😆

**Comment by Henningen22** [comment]
Habe die Datenbank mit realdatena us dem jahre 2013 befüllt, mir fehlen nurnoch ein paar tupel im bereich der 2stimme, dann lade ich sie hoch

**Comment by cybertschunk** [comment]
@HasseDosch @Henningen22 was ist denn jetzt der Stand? Bitte machen!

**Comment by Henningen22** [comment]
@AnonymOnline Die aktuellen daten für 2017 sind drinnen. Alles was geht.
