### ISSUE TITLE
A possibility to get the available elections

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#68]
The @infolk11/vwahl group needs a possibility, to see, which elections are available. So we need a list with all databases, fitting the [name-schema](https://github.com/infolk11/btw17/wiki/Namensschema-Datenbank).

**Comment by ghost** [comment]
I tried several methods I found on my local MySQL instance, but none of them work. For instance, I found the following querys:
SELECT name FROM master.dbo.sysdatabases;
select * from sys.databases WHERE name NOT IN ('master', 'tempdb', 'model', 'msdb'); 
EXEC sp_databases;
Could you please try them out on the server? If they don't work, than I'm out of ideas.

**Comment by cybertschunk** [comment]
You can  use `SHOW DATABASES` to get a result set with all databases. With `SHOW DATABAES LIKE [FILTER]` you can filter the result.
