### ISSUE TITLE
Kandidaten brauchen auch eine Farbe

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#76]
Die Kandidaten brauchen auch eine Farbe. @infolk11/database könnt ihr euch um einen entsprechenden Eintrag kümmern?
@infolk11/querys überarbeitet ihr dann die Abfragen?

**Comment by ghost** [comment]
Es wäre super, wenn @infolk11/database das spätestens Montag fertig hätte, damit wir uns dann noch rechtzeitig um die Überarbeitung der Abfragen kümmern können.

**Comment by Henningen22** [comment]
Habe die Farben eingefügt und werde huete die überarbeiteten beispieldaten hochladen.
