### ISSUE TITLE
Replace log4cpp with QDebug - very important!

### ISSUE THREAD

**Issue by HasseDosch** [AnonymOnline/btw17#85]
outpatch log4cpp and replace it with qdebug or something equal. This includes writing a new logger functionality and adjusting the logger calls in the program to the new logger.

**Comment by HasseDosch** [comment]
@Steve-F333 please reference this issue by including #85 in the description in your merge-request.

**Comment by cybertschunk** [comment]
@Steve-F333 the actual code is not compileable. Please make sure that your local development system fits the requierments specified in https://github.com/infolk11/btw17/wiki/Dependencies

**Comment by cybertschunk** [comment]
Fixed with pull request #91
