### ISSUE TITLE
Datenbankfehler

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#9]
Es gibt eine Reihe Fehler in der Datenbank. Sie sind hier aufgeführt:
- Farbe muss maschinenlesbar sein.
- Wahlbeteiligung im Wahllokal ist falsch geschrieben
- Wir brauchen ein Namensschema für die Datenbank
- Was ist die Bedeutung von Listenplaetze in Partei

**Comment by cybertschunk** [comment]
@Karl168 @Henningen22 Außerdem fügt bitte noch einige mehr Beispieldatensätze in die Datenbank ein.

**Comment by ghost** [comment]
@Karl168 @Henningen22 Wenn ich es richtig sehe, dann kann man in der Tabelle 1stimme keine weiteren Daten aus anderen Wahllokalen einspeisen, da D_ID ein UNIQUE KEY ist.

**Comment by Henningen22** [comment]
Ich werde mich mal eben dran machen und die fehler begutachten ;)

**Comment by KimPP** [comment]
@Henningen22 @Karl168 Die Tabellenspalte(n), die 'Name' heißen, bitte in 'Nachname' oder ähnliches ändern, da 'name' bei meiner sql version als schlüssel gekennzeichnet wird und ich 'name' daher nicht als spaltenname angeben/verwenden kann.

**Comment by KimPP** [comment]
Noch ein sehr gravierender Fehler (!!!!) bitte dringendst beheben! Und zwar ist W_ID in den Tabellen 1stimme und 2 stimme Primärschlüssel, jedoch nicht eindeutig, da sowohl alle Direktkandidaten als auch alle Parteien in allen Wahllokalen gewählt werden können -> für jede W_ID werden alle Parteien bzw. Direktkandidaten aufgeführt (die dann _dieselbe_ W_ID erhalten). Denkt euch bitte etwas neues aus! Zur Not fügt einfach einen 'sinnlosen' Primärschlüssel ein, der sich mit jedem Eintrag um eins erhöht und einfach nur dazu da ist, die Datensätze eindeutig zu identifizieren. Weder W_ID noch D_ID noch P_ID werden eindeutig sein!!! @Henningen22 @Karl168

**Comment by cybertschunk** [comment]
> Wenn ich es richtig sehe, dann kann man in der Tabelle 1stimme keine weiteren Daten aus anderen Wahllokalen einspeisen, da D_ID ein UNIQUE KEY 

@Grasotus Das ist zumindest in der neueren Version nicht mehr der Fall. Siehe hierfür https://github.com/infolk11/btw17/blob/master/Database/wahl_17__1_2_sql.sql

**Comment by cybertschunk** [comment]
> P_ID muss als Fremdschlüssel bei Direktkandidaten eingefügt werden, sonst ist nicht ersichtlich, welche Partei welchen Direktkandidaten stellt/welcher Direktkandidat zu welcher Partei gehört.

@KimPP Da schließe ich mich dir an. Hierfür wurde jedoch bereits Issue #14 eröffnet.

**Comment by KimPP** [comment]
> fügt bitte noch einige mehr Beispieldatensätze in die Datenbank ein.

Ich erinnere nochmals daran, dass die Auswertungsgruppe diese Datensätze wirklich braucht!!! Wir können sonst nicht überprüfen, ob unsere SQL-Statements auch funktionieren. Bitte fügt dabei direkt alle Parteien, Direktkandidaten und Wahllokale ein, soweit sie schon sicher feststehen! Dann macht ihr euch nicht zusätzliche Arbeit ;D @Karl168 @Henningen22 Und soweit ich es richtig gesehen habe, ist für W_Beteiligung angegeben, dass die Spalte nicht leer sein darf (not null). Allerdings gebt ihr doch die Daten für die Wahllokale VOR der Wahl ein, also noch bevor es überhaupt Ergebnisse für die Wahlbeteiligung gibt, oder? Wenn das so ist, dann muss diese Spalte leer sein dürfen, sonst bekommt ihr Probleme beim eingeben der Datensätze. Korrigiert mich, wenn ich falsch liege!

**Comment by cybertschunk** [comment]
Wenn ihr euch noch ein Namensschema überlegt, kann ich diesen Issue endlich schließen.

**Comment by cybertschunk** [comment]
Dieser Issue ist jetzt in #63 aufgegangen.
