### ISSUE TITLE
Beispieldatensaetze.sql nicht importierbar

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#97]
Bitte Beispieldatensaetze.sql auf die aktuelle Tabelle anpassen und unter Angabe dieses Issues auf GitHub hochladen

**Comment by cybertschunk** [comment]
Bzw. brauchen wir von der Visualisierung halt demohafte Wahlergebnisse um unser Programm testen zu können. Wenn ihr ein SQL-File schreibt, indem ihr diese bereitstellt und das wir einfach importieren können wäre uns sehr gehofen.

**Comment by sidde-jpg** [comment]
Wir kümmern uns darum. 💋

**Comment by Henningen22** [comment]
Ja das ist mir auch aufgefallen. Das ist das Problem was ich mit Daniel vorhatte zu klären. Es liegt an den Tabellen 1stimme und 2stimme, da angeblich irgendwelche fremdschlüsselbedingungen nicht erfüllt werden.

**Comment by Henningen22** [comment]
Im Moment kann ich es nicht beheben weil meine Mutter in meinem Zimmer pennt... warum auch immer... morgen bin ich dran.

**Comment by cybertschunk** [comment]
@Henningen22 das ist gerade echt wichtig. Bitte so schnell wie möglich, spätestens bis Freitag fixen.

**Comment by cybertschunk** [comment]
Sry für den Zeitdruck aber sonst können wir nicht richtig weiterarbeiten.

**Comment by Henningen22** [comment]
Ich verstehe die Dringlichkeit! Ran da!

**Comment by cybertschunk** [comment]
Fixed with #106
